version: '3.8'

services:
  mcp-atlassian-server:
    build:
      context: ./mcp-atlassian
      dockerfile: Dockerfile
    container_name: mcp-atlassian-server
    ports:
      - "8001:8000"
    environment:
      # Atlassian Jira Configuration
      - ATLASSIAN_JIRA_URL=${ATLASSIAN_JIRA_URL}
      - ATLASSIAN_JIRA_USERNAME=${ATLASSIAN_JIRA_USERNAME}
      - ATLASSIAN_JIRA_TOKEN=${ATLASSIAN_JIRA_TOKEN}
      
      # Atlassian Confluence Configuration
      - ATLASSIAN_CONFLUENCE_URL=${ATLASSIAN_CONFLUENCE_URL}
      - ATLASSIAN_CONFLUENCE_USERNAME=${ATLASSIAN_CONFLUENCE_USERNAME}
      - ATLASSIAN_CONFLUENCE_TOKEN=${ATLASSIAN_CONFLUENCE_TOKEN}
      
      # MCP Server Configuration
      - MCP_TRANSPORT=streamable-http
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge